version: '3.5'

services:
  db:
    container_name: db
    image: mysql:5.7
    ports:
      - '6033:3306'
    env_file:
      - ./secrets/db.env
    volumes:
      - ./data/sql:/docker-entrypoint-initdb.d
      - ./data/mysql:/var/lib/mysql

  django:
    depends_on:
      - db
    env_file:
      - ./secrets/db.env
    environment:
      DEBUG: 1
      EMAIL_SERVICE_NAME: mailchimp
      EMAIL_NEWSLETTER_LIST_ID: d574cb485f
