version: '3.5'

services:
  db:
    image: postgres
    container_name: db2
    ports:
      - '5432:5432'
    env_file:
      - ./secrets/db.env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  
  django:
    depends_on:
      - db
    env_file:
      - ./secrets/db.env
    environment:
      DEBUG: 1
      EMAIL_SERVICE_NAME: mailchimp
      EMAIL_NEWSLETTER_LIST_ID: d574cb485f
      DATABASE_HOST: db
