version: '3.5'

services:
  django:
    container_name: api
    build: ./api
    command: python hackathonmentors/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./api:/api
    ports:
      - "8000:8000"
    secrets:
      - django_secret
    depends_on:
      - db
    env_file:
      - ./secrets/db.env
    environment:
      DEBUG: 1
      DJANGO_SECRET_KEY: /var/run/secrets/django_secret
      EMAIL_SERVICE_NAME: mailchimp
      EMAIL_NEWSLETTER_LIST_ID: d574cb485f
      DATABASE_HOST: db

  db:
    image: postgres
    container_name: db
    ports:
      - '5432:5432'
    env_file:
      - ./secrets/db.env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      
    

secrets:
  django_secret:
    file: ./secrets/django_secret
