version: '3.5'

services:
  django:
    container_name: hackathonmentors
    build: ./api
    command: python hackathonmentors/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./api:/build
    ports:
      - "8000:8000"
    environment:
      DJANGO_SECRET_KEY: /var/run/secrets/django_secret
      EMAIL_SERVICE_NAME: mailchimp
      EMAIL_NEWLETTER_LIST_ID: d574cb485f
    secrets:
      - django_secret

  web:
    image: node:15.8.0
    command: sh entrypoint.sh
    working_dir: /web
    volumes:
      - ./web:/web

  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - ./web/build:/var/www/frontend # maps frontend build inside nginx
    depends_on:
      - django


secrets:
  django_secret:
    file: ./secrets/django_secret
