version: '3.5'

services:
  web:
    container_name: hackathonmentors
    build: .
    command: python hackathonmentors/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/build
    ports:
      - "8000:8000"
    environment:
      DJANGO_SECRET_KEY: /var/run/secrets/django_secret
      EMAIL_SERVICE_NAME: mailchimp
      EMAIL_NEWLETTER_LIST_ID: d574cb485f
    secrets:
      - django_secret

secrets:
  django_secret:
    file: ./secrets/django_secret
