# Generated by Django 3.0.7 on 2020-06-22 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0002_add_fields_slug_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackathon',
            name='created',
        ),
        migrations.AddField(
            model_name='hackathon',
            name='is_remote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='link',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
