# Generated by Django 3.0.5 on 2020-05-16 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='slug',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
