# Generated by Django 3.0.7 on 2020-07-12 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0003_auto_20200622_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='img',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
