# Generated by Django 3.1.12 on 2021-09-16 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0003_remove_mentor_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='name',
        ),
    ]
