# Generated by Django 3.1.13 on 2023-06-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mentor", "0002_rename_userid_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="mentor",
            name="is_official",
            field=models.BooleanField(default=False),
        ),
    ]
