# Generated by Django 3.1.13 on 2023-06-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0001_initial'),
        ('mentor', '0004_mentor_is_official'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='skills',
            field=models.ManyToManyField(to='skill.UserSkill', verbose_name='User skills'),
        ),
    ]
