# Generated by Django 3.1.13 on 2023-06-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0001_initial'),
        ('mentor', '0005_mentor_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='skills',
            field=models.ManyToManyField(blank=True, to='skill.UserSkill', verbose_name='User skills'),
        ),
    ]
