# Generated by Django 3.0.7 on 2020-06-28 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentor',
            old_name='user_id',
            new_name='user',
        ),
    ]
