# Generated by Django 3.1.12 on 2021-09-07 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0002_rename_userid_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='skills',
        ),
    ]
